server:
  port: 9393

spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/amitbdj1481/configserver
          clone-on-start: true
